package com.myteam.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DATAOBJECT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "DATAOBJECT_ID_SEQ", name = "DATAOBJECT_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "empid")
	private java.lang.Integer empid;

	public dataObject() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(java.lang.Integer empid) {
		this.empid = empid;
	}

	public dataObject(java.lang.Long id, java.lang.String name,
			java.lang.Integer empid) {
		this.id = id;
		this.name = name;
		this.empid = empid;
	}

}